# Generated by Django 2.2.1 on 2020-04-24 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_msg', models.CharField(blank=True, max_length=128, null=True)),
                ('last_msg_time', models.DateTimeField(auto_now=True)),
                ('msg_type', models.IntegerField(default=0)),
                ('msg_count', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=1)),
                ('user_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_one', to=settings.AUTH_USER_MODEL)),
                ('user_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_two', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户会话表',
                'verbose_name_plural': '用户会话表',
                'db_table': 'User_chat',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=255)),
                ('type', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=1)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_msg.UserChat')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_to_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
                'db_table': 'message',
            },
        ),
    ]
