# Generated by Django 2.2.1 on 2020-04-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_msg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchat',
            name='user1_msg_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userchat',
            name='user2_msg_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userchat',
            name='last_msg_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
